spring:
  application:
    name: Chronify
  #mysql connection configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chronify
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-handlers-package: org.example.typehandler

pagehelper:
  reasonable: true
  helper-dialect: mysql

#spring transaction management log
logging:
    level:
      org.springframework.jdbc.support.JdbcTransactionManager: debug